### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ofcansh** [DarkThunder99/Bot-with-Dashboard#1]
Error: The module '/home/runner/TexturePack/node_modules/canvas/build/Release/canvas.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/TexturePack/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)Hint: hit control+c anytime to enter REPL.
[SQL] Connected to the MySQL server! Connection ID: 5586181
[SQL] Fetched table `logs`! Status: Success
[SQL] Fetched table `welcome`! Status: Success
[SQL] Fetched table `reputation`! Status: Success
[SQL] Fetched table `leave`! Status: Success
[SQL] Fetched table `stats`! Status: Success
/home/runner/TexturePack/node_modules/mysql/lib/protocol/Parser.js:437
      throw err; // Rethrow non-MySQL errors
      ^

Error: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'JSON NOT NULL, PRIMARY KEY (`id`))' at line 1
    at Query.<anonymous> (/home/runner/TexturePack/index.js:51:17)
    at Query.<anonymous> (/home/runner/TexturePack/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/home/runner/TexturePack/node_modules/mysql/lib/Connection.js:488:16)
    at Query.Sequence.end (/home/runner/TexturePack/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/home/runner/TexturePack/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/home/runner/TexturePack/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/runner/TexturePack/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/runner/TexturePack/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/runner/TexturePack/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/runner/TexturePack/node_modules/mysql/lib/Connection.js:88:28)
repl process died unexpectedly: exit status 1


**Comment by ofcansh** [comment]
how do i fix this?

**Comment by danekxd** [comment]
seems like some modules are missing or sql version error

**Comment by ofcansh** [comment]
but i did as he told in his video ... i did the same to same work as he did :]
